# Generated by Django 5.2.1 on 2025-05-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('codigo', models.EmailField(max_length=254)),
                ('direccion', models.CharField()),
                ('disposicion', models.IntegerField(max_length=10)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField()),
                ('procedimiento', models.CharField()),
                ('url', models.CharField()),
            ],
        ),
    ]
