# Generated by Django 5.2.1 on 2025-05-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='asunto',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='disposicion',
            field=models.CharField(),
        ),
    ]
