# Generated by Django 5.2.1 on 2025-05-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documentos_asunto_alter_documentos_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('disposicion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=255)),
                ('procedimiento', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='documentos',
        ),
    ]
